[package]
name = "replit-takeout"
version = "0.1.0"
edition = "2021"
authors = ["Ben Dixon <malted@malted.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.5"
graphql_client = { version = "0.14.0", features = ["reqwest", "reqwest-blocking"] }
log = "0.4.22"
reqwest = { version = "0.12.5", features = ["blocking", "cookies", "json"] }
serde = "1.0.208"
