[package]
name = "replit-takeout"
version = "0.1.0"
edition = "2021"
authors = ["Ben Dixon <malted@malted.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
airtable-api = "0.1.36"
crosis = { git = "https://github.com/PotentialStyx/crosis-rust.git", version = "0.1.0" }
dotenv = "0.15.0"
env_logger = "0.11.5"
flume = "0.11.0"
graphql_client = { version = "0.14.0", features = ["reqwest", "reqwest-blocking"] }
lettre = { version = "0.11.7", features = ["tokio1", "tokio1-native-tls"] }
log = "0.4.22"
once_cell = "1.19.0"
reqwest = { version = "0.12.5", features = ["blocking", "cookies", "json"] }
resend-rs = "0.9.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.208"
serde_json = "1.0.125"
tokio = { version = "1.39.3", features = ["macros", "net", "rt-multi-thread"] }
