apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: replit-takeout
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: replit-takeout
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
